# Represents a list of audit log events that a Discord app may receive
class_name AuditLogEvent

const GUILD_UPDATE = 1 # Server settings were updated
const CHANNEL_CREATE = 10 # Channel was created
const CHANNEL_UPDATE = 11 # Channel settings were updated
const CHANNEL_DELETE = 12 # Channel was deleted
const CHANNEL_OVERWRITE_CREATE = 13 # Permission overwrite was added to a channel
const CHANNEL_OVERWRITE_UPDATE = 14 # Permission overwrite was updated for a channel
const CHANNEL_OVERWRITE_DELETE = 15 # Permission overwrite was deleted from a channel
const MEMBER_KICK = 20 # Member was removed from server
const MEMBER_PRUNE = 21 # Members were pruned from server
const MEMBER_BAN_ADD = 22 # Member was banned from server
const MEMBER_BAN_REMOVE = 23 # Server ban was lifted for a member
const MEMBER_UPDATE = 24 # Member was updated in server	Member
const MEMBER_ROLE_UPDATE = 25 # Member was added or removed from a role
const MEMBER_MOVE = 26 # Member was moved to a different voice channel
const MEMBER_DISCONNECT = 27 # Member was disconnected from a voice channel
const BOT_ADD = 28 # Bot user was added to server
const ROLE_CREATE = 30 # Role was created
const ROLE_UPDATE = 31 # Role was edited
const ROLE_DELETE = 32 # Role was deleted
const INVITE_CREATE = 40 # Server invite was created
const INVITE_UPDATE = 41 # Server invite was updated
const INVITE_DELETE = 42 # Server invite was deleted
const WEBHOOK_CREATE = 50 # Webhook was created
const WEBHOOK_UPDATE = 51 # Webhook properties or channel were updated
const WEBHOOK_DELETE = 52 # Webhook was deleted
const EMOJI_CREATE = 60 # Emoji was created
const EMOJI_UPDATE = 61 # Emoji name was updated
const EMOJI_DELETE = 62 # Emoji was deleted
const MESSAGE_DELETE = 72 # Single message was deleted
const MESSAGE_BULK_DELETE = 73 # Multiple messages were deleted
const MESSAGE_PIN = 74 # Message was pinned to a channel
const MESSAGE_UNPIN = 75 # Message was unpinned from a channel
const INTEGRATION_CREATE = 80 # App was added to server
const INTEGRATION_UPDATE = 81 # App was updated (as an example, its scopes were updated)
const INTEGRATION_DELETE = 82 # App was removed from server
const STAGE_INSTANCE_CREATE = 83 # Stage instance was created (stage channel becomes live)
const STAGE_INSTANCE_UPDATE = 84 # Stage instance details were updated
const STAGE_INSTANCE_DELETE = 85 # Stage instance was deleted (stage channel no longer live)
const STICKER_CREATE = 90 # Sticker was created
const STICKER_UPDATE = 91 # Sticker details were updated
const STICKER_DELETE = 92 # Sticker was deleted
const GUILD_SCHEDULED_EVENT_CREATE = 100 # Event was created
const GUILD_SCHEDULED_EVENT_UPDATE = 101 # Event was updated
const GUILD_SCHEDULED_EVENT_DELETE = 102 # Event was cancelled
const THREAD_CREATE = 110 # Thread was created in a channel
const THREAD_UPDATE = 111 # Thread was updated
const THREAD_DELETE = 112 # Thread was deleted
const APPLICATION_COMMAND_PERMISSION_UPDATE = 121 # Permissions were updated for a command
const AUTO_MODERATION_RULE_CREATE = 140 # Auto Moderation rule was created
const AUTO_MODERATION_RULE_UPDATE = 141 # Auto Moderation rule was updated
const AUTO_MODERATION_RULE_DELETE = 142 # Auto Moderation rule was deleted
const AUTO_MODERATION_BLOCK_MESSAGE = 143 # Message was blocked by AutoMod (according to a rule)
